id: P007965
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:08.694745
source_metadata:
  id: bdr:W23707
  title: རྒྱུད་སྡེ་སྤྱི་རྣམ་གསལ་བྱེད་སོགས
  author: ''
  volumes:
    9434a19355574778b5892f1b2c0c1eb8:
      image_group_id: I2482
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
