id: P007965
initial_creation_type: ocr
source_metadata:
  id: bdr:W23707
  title: རྒྱུད་སྡེ་སྤྱི་རྣམ་གསལ་བྱེད་སོགས
  author: ''
  volumes:
    9434a19355574778b5892f1b2c0c1eb8:
      image_group_id: I2482
      title: ''
      volume_number: 1
      total_pages: 328
ebook_metadata:
  title: རྒྱུད་སྡེ་སྤྱི་རྣམ་གསལ་བྱེད་སོགས
  author: ''
  sku: P007965
  cover: cover.jpg
  layers:
  - pagination
