id: I1E9B9826
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:37:19+00:00'
last_modified: '2022-06-09T08:05:00.279917+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23707
  title: རྒྱུད་སྡེ་སྤྱི་རྣམ་གསལ་བྱེད་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    52C2:
      image_group_id: I2482
      title: ''
      total_pages: 328
      order: 1
      base_file: 52C2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
